// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.6
// source: api/ping-service/v1/services/ping.service.v1.proto

package servicev1

import (
	context "context"
	resources "github.com/my-saas-platform/saas-api-proto/api/ping-service/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SrvPingV1_Ping_FullMethodName = "/saas.api.ping.servicev1.SrvPingV1/Ping"
)

// SrvPingV1Client is the client API for SrvPingV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvPingV1Client interface {
	// Ping ping
	Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error)
}

type srvPingV1Client struct {
	cc grpc.ClientConnInterface
}

func NewSrvPingV1Client(cc grpc.ClientConnInterface) SrvPingV1Client {
	return &srvPingV1Client{cc}
}

func (c *srvPingV1Client) Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error) {
	out := new(resources.PingResp)
	err := c.cc.Invoke(ctx, SrvPingV1_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvPingV1Server is the server API for SrvPingV1 service.
// All implementations must embed UnimplementedSrvPingV1Server
// for forward compatibility
type SrvPingV1Server interface {
	// Ping ping
	Ping(context.Context, *resources.PingReq) (*resources.PingResp, error)
	mustEmbedUnimplementedSrvPingV1Server()
}

// UnimplementedSrvPingV1Server must be embedded to have forward compatible implementations.
type UnimplementedSrvPingV1Server struct {
}

func (UnimplementedSrvPingV1Server) Ping(context.Context, *resources.PingReq) (*resources.PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSrvPingV1Server) mustEmbedUnimplementedSrvPingV1Server() {}

// UnsafeSrvPingV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvPingV1Server will
// result in compilation errors.
type UnsafeSrvPingV1Server interface {
	mustEmbedUnimplementedSrvPingV1Server()
}

func RegisterSrvPingV1Server(s grpc.ServiceRegistrar, srv SrvPingV1Server) {
	s.RegisterService(&SrvPingV1_ServiceDesc, srv)
}

func _SrvPingV1_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvPingV1Server).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrvPingV1_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvPingV1Server).Ping(ctx, req.(*resources.PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvPingV1_ServiceDesc is the grpc.ServiceDesc for SrvPingV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvPingV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saas.api.ping.servicev1.SrvPingV1",
	HandlerType: (*SrvPingV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SrvPingV1_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ping-service/v1/services/ping.service.v1.proto",
}
